Update to hopefully building version of rust-actix-utils.
TODO:
error[E0523]: found two different crates with name `mio` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
 --> src/accept.rs:4:5
  |
4 | use mio::{Interest, Poll, Token as MioToken};
x

- new package definition
- add new dependencies to %extra-inputs